"""Initial schema bootstrap.

For V1 the initial migration materialises the full ORM schema via
``metadata.create_all``. This keeps the first migration reliable across the many
tables/enums and is appropriate for a fresh install. Subsequent schema changes
should use normal Alembic autogenerated migrations (``alembic revision
--autogenerate``), which diff against this state.
"""
from __future__ import annotations

from alembic import op

from app.models import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
